# Generated by Django 5.2.8 on 2025-11-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaces',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='mac',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('server', 'Server'), ('network', 'Network Device')], max_length=50),
        ),
    ]
