# Generated by Django 5.2.8 on 2025-11-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_alter_workplaces_ip_alter_workplaces_mac_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="workplaces",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workplaces.department",
                verbose_name="Тип Рабочего Места:",
            ),
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="description",
            field=models.TextField(verbose_name="Описание Рабочего Места:"),
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название Рабочего Места:"
            ),
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="type",
            field=models.CharField(
                choices=[
                    ("nopcplace", "Место без компьютера"),
                    ("pcplace", "Место с компьютером"),
                ],
                max_length=50,
                verbose_name="Тип Рабочего Места:",
            ),
        ),
    ]
