# Generated by Django 5.2.8 on 2025-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0003_alter_department_options_alter_staff_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workplaces",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
